blueprint:
  name: Sync Light and Multiple Switches
  description: >
    Synchronize the state of a light and multiple switches. If the light or any switch changes,
    all others are set to the same state (on or off).
  domain: automation
  input:
    light_entity:
      name: Light
      description: The light to sync
      selector:
        entity:
          domain: light
    switch_entities:
      name: Switches
      description: The switches to sync with the light
      selector:
        entity:
          domain: switch
          multiple: true

trigger:
  - platform: state
    entity_id: !input light_entity
  - platform: state
    entity_id: !input switch_entities

condition: []

action:
  - variables:
      light: !input light_entity
      switches: !input switch_entities
      trigger_entity: "{{ trigger.entity_id }}"
      new_state: "{{ trigger.to_state.state }}"

  - choose:
      - conditions: "{{ new_state in ['on', 'off'] }}"
        sequence:
          - service: homeassistant.turn_{{ new_state }}
            target:
              entity_id: >
                {% set all_entities = [light] + switches %}
                {% set others = all_entities | reject('equalto', trigger_entity) | list %}
                {{ others }}

mode: parallel
